services:
    db:
        image: postgres:17.2-alpine
        restart: always
        environment:
            POSTGRES_DB: 'cinema'
            POSTGRES_USER: 'spring'
            POSTGRES_PASSWORD: 'spring'
        ports:
            - '5434:5432'
        volumes:
            - db-data:/var/lib/postgresql/data
    test-db:
        image: postgres:17.2-alpine
        restart: always
        environment:
            POSTGRES_DB: 'cinema-test'
            POSTGRES_USER: 'spring'
            POSTGRES_PASSWORD: 'spring'
        ports:
            - '5436:5432'
volumes:
    db-data: